### ISSUE TITLE
Cannot Reproduce the Inference Speed.

### ISSUE THREAD

**Issue by csguoh** [czg1225/CoDe#4]
Hi, authors,

Thanks for sharing this awesome work. I have run the sampling process by running `./sample_CoDe.py` to generate 50,000 images on one 3090GPU. However, I find the actual inference speed on my implementation is even slower than the original VAR. For instance, The original VAR (d=24) takes about 1h14min to finish the whole sampling, while the sampling of CoDe takes over 4h to finish. 

Can you give me some hints to reproduce the inference speed in the paper? thanks.

**Comment by czg1225** [comment]
Hi @csguoh,
In the sampling code, we set batchsize=1 (random seed from 0 t0 49 to generate 50 images per class) to reproduce the FID of the original VAR. As a result, the inference speed is not fast as the batch size is small.

If you want to compare the inference efficiency, please use the `infer_original.py` and `infer_CoDe.py`. Thanks!

**Comment by csguoh** [comment]
Hi, authors
Thanks for your reply. As suggested, I tried to test the inference speed with `infer_original.py` and `infer_CoDe.py`. The results are as follows:

1. for `infer_original.py` (I used the d=24 VAR model):
![image](https://github.com/user-attachments/assets/2ce7f32d-5368-4afd-8df5-bb646ff25da9)


2. for `infer_CoDe.py`: 
![image](https://github.com/user-attachments/assets/fca388a2-6de5-43d9-882c-03426721aa56)

It seems there is still no inference acceleration on my local server. I have no idea about this results. Does it has anything to do with the environment? I use 3090 GPU with torch 2.1.0.

**Comment by czg1225** [comment]
Hi @csguoh ,
Our speedup is compared to the original VAR-30. Compared to the original VAR-d30, our method achieves a 1.7x speedup and reduces memory usage to 0.5x with a batch size of 64, while the FID score only slightly increases from 1.95 to 1.98. The efficiency gains of our method become more pronounced as the batch size increases, as CoDe significantly reduces memory consumption associated with the KV cache and activations.

More comprehensive experimental results can be found in our paper.

**Comment by czg1225** [comment]
In addition, compared to VAR-24 and VAR-20, our method achieves a better FID at a similar inference speed, as demonstrated in Table 1 of our paper.

**Comment by csguoh** [comment]
Hi, authors.

Thanks for your reply. As shown in the paper as well as the results provided above, the CoDe runs similar speed as the original d=24 VAR model but exhibit performance as the d=30 VAR model. I have test the inference speed of d=30 VAR model as below. 
![image](https://github.com/user-attachments/assets/61b2fb8e-46e6-4b05-b169-c1f172746247)

And it shows CoDe is faster than this setup (1.15s v.s. 1.70s with bs=16, maybe the GPU type causes the discrepancy on the inference time).

My question has been solved. Thanks again for the discussion!

**Comment by czg1225** [comment]
Hi @csguoh ,

To perfectly reproduce the inference speedup results, please note the following two points:

1. We test the inference speed with a batch size of 64. A larger batch size will lead to better GPU utilization, and our method exhibits greater acceleration when processing more tokens during inference.

2. In our paper, the inference speed is evaluated excluding the VAE decoder's time cost. This is clarified in the experimental section of our paper. This is a fair comparison, as the inference speeds for all methods (including VAR-30, VAR-24, VAR-20, dit, llamagen.....) are measured without including the VAE time cost. This is a shared cost for all methods

**Comment by czg1225** [comment]
Additionally, the GPU type may also cause differences as you said.
